platform: x64
configuration: Release
image: Visual Studio 2017

build:
  parallel: true                  # enable MSBuild parallel builds
  project: build\JEM_vc2017.sln   # path to Visual Studio solution or project

artifacts:
  - path: bin\vc2017\x64\Release\libJEMDecoder.dll

deploy:
  provider: GitHub
  auth_token:
    secure: boWJ9aVfVBpOkBGzWF5yS5/Os3eDUjFfziOY04+LNA+7v+PnMFBtHeMJe2PjK4gm
  artifact: bin\vc2017\x64\Release\libJEMDecoder.dll # the dll
  on:
    appveyor_repo_tag: true        # deploy on tag push only
