language: cpp
matrix:
  include:
  - os: linux
    dist: trusty
    env: DEPLOY_FILE=lib/libJEMDecoder.so
  - os: osx
    env: DEPLOY_FILE=lib/libJEMDecoder.dylib
compiler:
- gcc
script:
- cd build/linux
- make
- cd ..
- cd ..
before_deploy:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then mv lib/liblibJEMDecoderStatic.so lib/libJEMDecoder.so; fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then mv lib/liblibJEMDecoderStatic.dylib lib/libJEMDecoder.dylib; fi
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: TMfW/EvFi0pF85BMk7kpB6THMZ5h36GmVuvBve3M0KGbayma7c4k0UosZqQfbdIB2VFkaPE7LfWNFSx9KONtU7rGVac/nbImZpbtMGvZBVFMDx9tO46DneVi4m+AgFUoRh3FMrOT6G7ekkMJx50xZ1Qq9Ien6/ygXGNxfUAaoEm23d6e4dAbDTLIW84GTyD5QllAro9JX+OVXKyiy76gLoNx0dtOgIEcZXd1+otv3w7MjgSX6lJGlkxIeh7KHGjZ5ewpDbQ8hfEqf/wU4WIU5Y1MMrVkpYUGFQDTpE56HkEvWwmLV6Eo2A2lxtCYcHXf8vuFSywe0sCYNQAuNxy0Vsr+5bauN8eW8owRFJr6HT3nZgmXSvaHpKFsbvtJ9xpVyrLsjy51HURLPwYAr82O5eizJta7KqQdQiMZFBwBKZ7ZLagMr+pPPm8RAAFfSk0HZBwNdtY/PfunaIe+vlKYWD9JXNRw5bCDUZ9eVj52SITULi/2lBoDfVJp6h0nfSP48rc8aRwg5G3tuUvDkhDJKqzzRMGQE+MphM89cE3cd0tcUnsV8hWvmfN4moa+lWQJa7Q8eJ7w6upJW9+ONzUw98UqpzmVlAh4P4X3IieO82PefmUq3Vw+Qz4KIFEvlMhIbQCdGlYY1udcqOFZj3eY/QFgccsRZ5eluEYyMIeZ3w8=
  file: $DEPLOY_FILE
  on:
    repo: ChristianFeldmann/libJEM
    tags: true
